test_that("git_add_and_push genera error", {
  expect_error(git_add_and_push_all())
})
